### ISSUE TITLE
Browser simulation of Classic Lotka-Volterra with x0=100

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#83] opened 2014-04-12 19:10 UTC
When chaning the parameter x0 from 10 to 100 the simulation output is wrong. It looks as expected though for x0=99 or x0=103. Very strange...

![classicmodel](https://cloud.githubusercontent.com/assets/5444067/2687902/fd12e858-c275-11e3-845d-0d61b7104f38.png)

**Comment by dietmarw** [comment] 2017-11-16 17:16
The new serverside simulation now actually gives a compiler error log message for this case:
```
stdout            | info    | The initialization finished successfully without homotopy method.
DASKR--  AT T (=R1) AND STEPSIZE H (=R2) THE                                    
      In above,  R1 =   1.2897921767513E+02   R2 =   9.8055546548322E-14
DASKR--  ERROR TEST FAILED REPEATEDLY OR WITH ABS(H)=HMIN                       
stdout            | warning | DDASSL had repeated error test failures on the last attempted step.
stdout            | warning | can't continue. time = 128.979218
stdout            | info    | model terminate | Integrator failed. | Simulation terminated at time 128.979
```

**Comment by xogeny** [comment] 2017-11-16 17:41
Wow @dietmarw I was just about to see if this worked with the new server side approach only to find you already checked.

The issue is probably one of tolerance.  If you simulate `x0`=100 and `y0`=50 and you mouse over the trajectories you see that the predator population **goes negative**.  Somehow, the simulation carries on and recovers.  But if you give `y0` any lower values, I suspect the "anti-wolves" cause a singularity.

I'm going to close this because at least we get a proper error message now.  If somebody wants to tighten the tolerances for this example, I'd be fine with that.  But there will always be limits for how far apart the initial populations can be.

**Closed by xogeny** 2017-11-16 17:41 UTC
Labels: Browser Simulation
