### ISSUE TITLE
Rod_ForLoop rod segments lack convective heat transfer term

### ISSUE THREAD

**Issue by patello** [xogeny/ModelicaBook#357] opened 2017-08-30 12:34 UTC
In the model Rod_ForLoop on http://book.xogeny.com/behavior/arrays/oned/ the middle segments lack the convective heat transfer term.

Line 34 should be changed to: 
`    rho*V*C*der(T[i]) = (-h * (T[i] - Tamb))-k*A*(T[i]-T[i-1])/(L/n)-k*A*(T[i]-T[i+1])/(L/n);
`

**Comment by xogeny** [comment] 2017-09-03 13:55
Pretty sure this is a duplicate of #243.  If not, feel free to re-open.

Thanks.

**Closed by xogeny** 2017-09-03 13:55 UTC
