### ISSUE TITLE
Sponsor logos invisible in Firefox

### ISSUE THREAD

**Issue by pierre-haessig** [xogeny/ModelicaBook#403] opened 2018-01-08 13:13 UTC
Since the style updgrade, the sponsor logos are not visible when the homepage http://book.xogeny.com/ is viewed with Firefox (tested with Firefox ESR 52 and Nightly 59).

I tried to look at the document with the inspector, and it's not clear to me what's going on, except I spotted something weird with the sponsor link (`<a class="sponsorlink ....">` tag) inside the  `<div class="blue item level" style="display:flex ... ` container that contains each sponsor data. It seems Firefox sees some weird style data associated with this node. Here is an extract:

    data:text/css;charset=utf-8,a%5Bdata-url%5E%3D%22http%3A%2F
    %2Fpaid.outbrain.com%2Fnetwork%2Fredir%3F%22%5D%20%2B%20.author%2C%0A.sponsorlink
    %2C%0A%5Bclass%24%3D%22_banner-sponsor%22%5%7B
    ...
    display%3Anone!important%3B%7D

Most importantly, the last line is interpreted as `display:none !important` which effectively hides the link.  However, I have no idea where these many lines (related to add trackers ?) are coming from.

Also, there is a separate minor issue with sponsors: the  "Gold/Silver/Bronze Sponsors" headings are `<a>` tags, which make them clickable although they have no target. I believe they should be `<h*>` instead.

**Comment by xogeny** [comment] 2018-01-08 21:45
@pierre-haessig Do you have any kind of ad blocker running?  I ask because I am unable to reproduce this issue with Firefox 57.0.4 (which is the latest version) on MacOS.

You are correct about the `<a>` tags, but I created issue #404 for that problem.  So let's stick to the sponsor logo issue here.

It would be good if anybody can shed any light on when this issues is seen and how to reproduce it.

**Comment by mrtiller** [comment] 2018-01-08 22:34
I can see the logos running Firefox 52.5.3 ESR with the noscript addon running under Windows 7 with all critical Windows Updates installed.

**Comment by xogeny** [comment] 2018-01-09 08:13
OK, I'll close this for now.  If you figure out the actual criteria being used, feel free to re-open so we can evaluate whether there is a reasonable way to fix it.  In any case, I'll keep #404 open and fix it in the `0.6.x` release.

Thanks for reporting this and looking into it.

**Closed by xogeny** 2018-01-09 08:13 UTC

**Comment by pierre-haessig** [comment] 2018-01-09 08:17
Yes. It's probably more of a feature than a bug...
